### PR TITLE
Adding launch button. Airavata-3117

### PR DESCRIPTION
**Pull request by shivamriky**
Launch button calls the launch service and then emits to parent 
component which will refetch the experiment.

### CODE REVIEW

**Comment by shivamriky** [comment]
@machristie  After calling the launch service we have to re-fetch and re-render the experiment. For this purpose, I have emitted to the parent container and re-fetched the experiment.
Please let me know if you think there would be a better way to do this.

**Comment by machristie** [comment]
@shivamriky when the parent container gets the event, it can change launching to true, then ExperimentSummary could have a [watcher](https://vuejs.org/v2/guide/computed.html#Watchers) on `launching` and when it changes to true call `initPollingExperiment`.

**Comment by shivamriky** [comment]
> @shivamriky when the parent container gets the event, it can change launching to true, then ExperimentSummary could have a [watcher](https://vuejs.org/v2/guide/computed.html#Watchers) on `launching` and when it changes to true call `initPollingExperiment`.

Hello Marcus,

I have added the watch method and now it calling the polling function.

**Comment by machristie** [comment]
Thanks @shivamriky

**Pull request merged**
