### PR TITLE
Compute Resources

### PR DESCRIPTION
**Pull request by eldhomathulla**

### CODE REVIEW

**Comment by machristie** [comment]
@eldhomathulla thanks, this looks good. Can you resolve the conflicts? Thanks.

**Comment by machristie** [comment]
@eldhomathulla your branch has conflicts. You'll need to rebase or merge in master.

**Comment by machristie** [comment]
@eldhomathulla is it okay if I merge this?

**Comment by eldhomathulla** [comment]
yes

**Pull request merged**
