### PR TITLE
AIRAVATA-3577: Enabling to disregard node to cpu count in the experiment creation

### PR DESCRIPTION
**Pull request by dinukadesilva**

### CODE REVIEW

**Review by machristie — COMMENTED** [review]
This looks great @dinukadesilva ! I love the way it works, even better than I imagined!

I do have one feedback, I think we maybe want to not show the lock icon when cpuPerNode isn't configured for the queue. Here are a couple ideas:

1. only show the lock icon when cpuPerNode is > 0
2. show the lock icon but unlocked and disabled when cpuPerNode isn't > 0

Probably 1 is better, but maybe check with @eroma2014 .

**Comment by machristie** [comment]
Chatted with @eroma2014 , let's go with option 1, only show the lock when cpuPerNode is > 0.

**Comment by dinukadesilva** [comment]
@machristie I wonder how does it make a difference. Ideally validating the cpuPerNode is not a part of the lock button and we may get questions about why it's disabled or hidden. Or until someone types in it, they would never know there's a lock button.

**Comment by machristie** [comment]
@dinukadesilva The problem is that not all queues have cpuPerNode configured. For a queue that doesn't have cpuPerNode configured (default value of 0) there is no way to calculated cpus or nodes based on the other. So if the lock button is there but cpuPerNode isn't configured, users may expect that the cpus or nodes will be automatically calculated, however, that won't happen.

Does that help explain the situation?

**Comment by dinukadesilva** [comment]
Make sense @machristie. Thank you.

**Comment by dinukadesilva** [comment]
I just made the changes

**Review by machristie — APPROVED** [review]
Perfect!

**Pull request merged**
